name: 'Slack Merge Queue'
branding:
  icon: 'bell'
  color: 'green'
description: 'handles a merge queue within slack'
inputs:
  mode:
    description: 'mode of the action, changes behaviour based on mode'
    required: true
  channel:
    description: 'the channel to use as the queue'
    required: true
  init_trigger:
    description: 'the trigger keyword to add PR to queue'
    required: false
    default: '/merging'
  merge_ready_message:
    description: 'message for alerting next PR in the queue'
    required: false
    default: 'Last PR closed. This PR is now up for merge!'
  alert_message:
    description: 'message for alerting current PR in the queue'
    required: false
    default: 'build is complete. Time to merge!'
  icon_emoji:
    description: 'icon emoji for the bot'
    required: false
    default: ':robot_face:'
  only_when_current:
    description: 'ALERT MODE: only alert if PR is currently up for merge'
    required: false
    default: 'true'

outputs:
  status: 
    description: 'status of the build run'
  next_pr: 
    description: 'id number of next pull request in the queue'
runs:
  using: 'node12'
  main: 'src/index.js'