const DELIM = ' :: ';
const SEARCH_PREFIX = 'Q-PR';
const STATUS = {
  ALREADY_CLOSED: 'ALREADY_CLOSED',
  TRIGGER_NOT_FOUND: 'TRIGGER_NOT_FOUND',
  ALREADY_QUEUED: 'ALREADY_QUEUED',
  ADDED_TO_QUEUE: 'ADDED_TO_QUEUE',
  NOT_FOUND: 'NOT_FOUND',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  WATCHERS_UPDATED: 'WATCHERS_UPDATED',
};
const Q_STATUS = {
  MERGING: 'MERGING',
  MERGED: 'MERGED',
  CANCELLED: 'CANCELLED',
  STALE: 'STALE',
};

const ATTACH_PREFIX = {
  NOTIFY: 'notify:',
  DELETE_ON_CANCEL: 'delete_on_cancel:',
};

const WATCHERS_TITLE = 'Watchers';
const ATTACH_PREFIXES = [ATTACH_PREFIX.NOTIFY];

module.exports = {
  DELIM,
  SEARCH_PREFIX,
  STATUS,
  Q_STATUS,
  WATCHERS_TITLE,
  ATTACH_PREFIXES,
  ATTACH_PREFIX,
};
